---
- name: Deploy website-nginx app
  hosts: ec2-instance
  vars_files:
    - vars.yaml

  tasks:
    - name: build new image
      command: docker build -t abdallabahrawy/project-app .
      register: build_result
      ignore_errors: yes

    - name: Log build Result
      debug:
        var: build_result

    - name: run the container
      command: docker run -d abdallabahrawy/project-app
      register: running_result
      ignore_errors: yes

    - name: Log running Result
      debug:
        var: running_result

    - name: login to DockerHub 
      docker_login:
       username: "{{ dockerhub_username }}"
       password: "{{ dockerhub_password }}"
       registry: https://index.docker.io/v1/
       reauthorize: yes

    - name: pushing the image to DockerHub
      command: docker push abdallabahrawy/project-app
      ignore_errors: yes
